package com.hybrid.projectarea.domain.model

import com.google.gson.annotations.SerializedName

data class checkListTools(
    val reason: String,
    val additionalEmployees: String,
    val zone: String,
    val carabiner: String,
    val wireStripper: String,
    val crimper: String,
    val terminalCrimper: String,
    val files: String,
    val allenKeys: String,
    val readlineKit: String,
    val impactWrench: String,
    val dielectricTools: String,
    val cuttingTools: String,
    val forceps: String,
    val straightWrench: String,
    val frenchWrench: String,
    val saw: String,
    val silicone: String,
    val pulley: String,
    val tapeMeasure: String,
    val sling: String,
    val kit: String,
    val drillBits: String,
    val punch: String,
    val extractor: String,
    val wrenchSet: String,
    val braveDices: String,
    val cutter: String,
    val hammer: String,
    val largeToolBag: String,
    val mediumToolBag: String,
    val fallProtectionCar: String,
    val harness: String,
    val pressureWasher: String,
    val blower: String,
    val megommeter: String,
    val earthTester: String,
    val perimeterMeter: String,
    val manometer: String,
    val pyrometer: String,
    val laptop: String,
    val drill: String,
    val compass: String,
    val inclinometer: String,
    val flashlight: String,
    val powerMeter: String,
    val glueGun: String,
    val solderingGun: String,
    val stepLadder: String,
    val sprayer: String,
    val rj45Connector: String,
    val networkConsole: String,
    val networkAdapter: String,
    val hotStick: String,
    val rope75: String,
    val ladder: String,
    val extensionCord: String,
    val longCable: String,
    val padlock: String,
    val chains: String,
    val hose: String,
    val corporatePhone: String,
    val observation: String,
    val badTools: String,
    val goodTools: String
)

data class checkListMobile(
    val reason:String,
    val additionalEmployees: String,
    val zone: String,
    val km: String,
    val plate: String,
    val circulation: String,
    val technique: String,
    val soat: String,

    val hornState: String,
    val brakesState: String,
    val headlightsState: String,
    val intermitentlightState: String,
    val indicatorsState: String,
    val mirrorsState: String,
    val tiresState: String,
    val bumpersState: String,
    val temperatureGauge: String,
    val oilGauge: String,
    val fuelGauge: String,
    val vehicleCleanliness: String,
    val doorsState: String,
    val windshieldState: String,
    val engineState: String,
    val batteryState: String,

    val extinguisher: String,
    val firstAidKit: String,
    val cones: String,
    val jack: String,
    val spareTire: String,
    val towCable: String,
    val batteryCable: String,
    val reflector: String,
    val emergencyKit: String,
    val alarm: String,
    val chocks: String,
    val ladderHolder: String,
    val sidePlate: String,

    val observation: String,
    val front: String,
    val leftSide: String,
    val rightSide: String,
    val interior: String,
    val rearLeftTire: String,
    val rearRightTire: String,
    val frontRightTire: String,
    val frontLeftTire: String,
)

data class checklistDay(
    @SerializedName("personal_2") val personal2: String?,
    @SerializedName("zone") val zone: String,
    @SerializedName("power_meter") val powerMeter: String,
    @SerializedName("ammeter_clamp") val ammeterClamp: String,
    @SerializedName("cutting_pliers") val cuttingPliers: String,
    @SerializedName("nose_pliers") val nosePliers: String,
    @SerializedName("universal_pliers") val universalPliers: String,
    @SerializedName("tape") val tape: String,
    @SerializedName("cutter") val cutter: String,
    @SerializedName("knob_driver") val knobDriver: String,
    @SerializedName("screwdriver_set") val screwdriverSet: String,
    @SerializedName("allenkeys_set") val allenkeysSet: String,
    @SerializedName("thor_screwboard") val thorScrewboard: String,
    @SerializedName("helmet_flashlight") val helmetFlashlight: String,
    @SerializedName("freanch_key") val freanchKey: String,
    @SerializedName("pyrometer") val pyrometer: String,
    @SerializedName("laptop") val laptop: String,
    @SerializedName("console_cables") val consoleCables: String,
    @SerializedName("network_adapter") val networkAdapter: String,
    @SerializedName("observations") val observations: String?
)


data class checklistEpps(
    @SerializedName("helmet") val helmet: String,
    @SerializedName("chin_strap") val chinStrap: String,
    @SerializedName("windbreaker") val windbreaker: String,
    @SerializedName("vest") val vest: String,
    @SerializedName("safety_shoes") val safetyShoes: String,
    @SerializedName("tshirt_ls") val tshirtLs: String,
    @SerializedName("shirt_ls") val shirtLs: String,
    @SerializedName("jeans") val jeans: String,
    @SerializedName("coveralls") val coveralls: String,
    @SerializedName("jacket") val jacket: String,
    @SerializedName("dark_glasses") val darkGlasses: String,
    @SerializedName("clear_glasses") val clearGlasses: String,
    @SerializedName("overglasses") val overglasses: String,
    @SerializedName("dust_mask") val dustMask: String,
    @SerializedName("earplugs") val earplugs: String,
    @SerializedName("latex_oil_gloves") val latexOilGloves: String,
    @SerializedName("nitrile_oil_gloves") val nitrileOilGloves: String,
    @SerializedName("split_leather_gloves") val splitLeatherGloves: String,
    @SerializedName("precision_gloves") val precisionGloves: String,
    @SerializedName("cut_resistant_gloves") val cutResistantGloves: String,
    @SerializedName("double_lanyard") val doubleLanyard: String,
    @SerializedName("harness") val harness: String,
    @SerializedName("positioning_lanyard") val positioningLanyard: String,
    @SerializedName("carabiners") val carabiners: String,
    @SerializedName("ascenders") val ascenders: String,
    @SerializedName("sunscreen") val sunscreen: String,
    @SerializedName("ccip") val ccip: String,
    @SerializedName("claro") val claro: String,
    @SerializedName("vericom") val vericom: String
)

data class ChecklistHistory(
    val type :String,
    val created_at: String,
)